services:

  test-runner:
    build: .
    container_name: showdown-test-runner
    depends_on:
      chrome:
        condition: service_healthy
    environment:
      - SELENIUM_URL=http://chrome:4444/wd/hub
      - TEST_PASSWORD=${TEST_PASSWORD}
    command: pytest -v -s --browser chrome --headless

  chrome:
    image: selenium/standalone-chrome:latest
    container_name: showdown-chrome
    shm_size: 2gb

    healthcheck:
      test: [ "CMD-SHELL", "curl -fsS http://localhost:4444/status || exit 1" ]
      interval: 5s
      timeout: 5s
      retries: 20
      start_period: 10s