services:

  selenium-hub:
    image: selenium/hub:4.49.0

    ports:
      - "4442:4442"
      - "4443:4443"
      - "4444:4444"

    healthcheck:
      test: ["CMD", "curl", "-fsS", "http://localhost:4444/status"]
      interval: 5s
      timeout: 5s
      retries: 12
      start_period: 10s


  chrome:
    image: selenium/node-chrome:4.49.0

    shm_size: 2gb

    depends_on:
      selenium-hub:
        condition: service_healthy

    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_MAX_SESSIONS=1

    ports:
      - "7900:7900"


  firefox:
    image: selenium/node-firefox:4.49.0

    shm_size: 2gb

    depends_on:
      selenium-hub:
        condition: service_healthy

    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_MAX_SESSIONS=1

    ports:
      - "7901:7900"


  test-runner:
    build:
      context: .
      dockerfile: Dockerfile

    user: root

    environment:
      SELENIUM_URL: http://selenium-hub:4444/wd/hub
      TEST_PASSWORD: ${TEST_PASSWORD}

    depends_on:
      selenium-hub:
        condition: service_healthy

      chrome:
        condition: service_started

      firefox:
        condition: service_started

    command:
      [
        "pytest",
        "-v",
        "-s",
        "--browser", "${BROWSER:-chrome}",
        "--headless",
        "--env", "qa"
      ]

    volumes:
      - ./allure-results:/app/allure-results
      - ./screenshots:/app/screenshots
      - ./logs:/app/logs