services:

  selenium-hub:
    image: selenium/hub:4.49.0
    ports:
      - "4444:4444"
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://localhost:4444/status || exit 1"]
      interval: 5s
      timeout: 5s
      retries: 20
      start_period: 10s

  chrome:
    image: selenium/node-chrome:4.49.0

    shm_size: 2gb

    depends_on:
      selenium-hub:
        condition: service_healthy

    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_MAX_SESSIONS=1

  firefox:
    image: selenium/node-firefox:4.49.0

    shm_size: 2gb

    depends_on:
      selenium-hub:
        condition: service_healthy

    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_MAX_SESSIONS=1

  test-runner:
    build:
      context: .
      dockerfile: Dockerfile

    environment:
      SELENIUM_URL: http://selenium-hub:4444/wd/hub
      TEST_PASSWORD: ${TEST_PASSWORD}
      BROWSER: ${BROWSER}
      ENVIRONMENT: ${ENVIRONMENT}
      SUITE: ${SUITE}

    command: [
    "pytest",
    "-v",
    "-s",
    "-n", "2",
    "--browser", "${BROWSER}",
    "--env", "${ENVIRONMENT}",
    "-m", "${SUITE}",
    "--headless"
  ]