[pytest]
testpaths = Tests
python_files = test_*.py
python_classes = Test*
python_functions = test_*

markers =
    smoke: Critical business flow tests
    regression: Full regression tests
    sanity: Quick sanity validation

addopts = -v